services:
  base:
    image: base
    build:
      context: base
  hosted-ce:
    image: hub.opensciencegrid.org/mwestphall/hosted-ce
    build:
      context: hosted-ce
  hosted-ce-sshd:
    image: hub.opensciencegrid.org/mwestphall/hosted-ce-sshd
    build:
      context: hosted-ce-sshd
