[program:sshd]
user = root
# Writing directly into /etc/ssh overwrites some necessary config files,
# instead stage keys into /etc/ssh.orig.d and then copy to /etc/sh
command = sh -c '
  mkdir -p /mnt/ssh.orig/etc/ssh &&
  ssh-keygen -A -f /mnt/ssh.orig &&
  /bin/cp -p /mnt/ssh.orig/etc/ssh/* /etc/ssh/ &&
  chmod 400 /etc/ssh/*key &&
  /usr/sbin/sshd -D'
