[program:htcondor-ce]
# CE startup depends on sshd becoming available and must start after
# a remote processes has forwarded an agent to the container
command = sh -c '
  source /usr/local/bin/remote-site-setup.sh &&
  /usr/share/condor-ce/condor_ce_startup -f'

autorestart=true
startsecs=20

